"""init models

Revision ID: aa05daacd9a8
Revises:
Create Date: 2026-06-22 14:18:13.478595

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aa05daacd9a8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("authors",
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("books",
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("genre", sa.String(), nullable=False),
    sa.Column("status", sa.Enum("draft", "created", "processing", "ready", "retry", "failed", "archived", name="book_status"), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("m2m_books_authors",
    sa.Column("book_id", sa.UUID(), nullable=False),
    sa.Column("author_id", sa.UUID(), nullable=False),
    sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
    sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
    sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ),
    sa.ForeignKeyConstraint(["book_id"], ["books.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("m2m_books_authors")
    op.drop_table("books")
    op.drop_table("authors")
    # ### end Alembic commands ###
