"""add ix status, id to books

Revision ID: af231c5a6e7e
Revises: aa05daacd9a8
Create Date: 2026-06-26 11:14:26.352150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af231c5a6e7e'
down_revision: Union[str, Sequence[str], None] = 'aa05daacd9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_books_status_id', 'books', ['status', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_status_id', table_name='books')
    # ### end Alembic commands ###
